{
TEST_MESSAGE("Vlozeni elementu: 1, 3 ,4")
TEST_OPERATION(set_insert)
TEST_INPUTS(1, 3 ,4)
TEST_OUTPUT(1, 1, 1)
TEST_REPORT_AFTER
TEST_PRINT_MEMORY_STATS
},

{
TEST_MESSAGE("Vlozeni elementu: 259 (tj. 3+256)")
TEST_OPERATION(set_insert)
TEST_INPUTS(259)
TEST_OUTPUT(1)
TEST_REPORT_AFTER
TEST_PRINT_MEMORY_STATS
},

{
TEST_MESSAGE("Odebrani elementu: 3")
TEST_OPERATION(set_erase)
TEST_INPUTS(3)
TEST_OUTPUT(1)
TEST_REPORT_BEFORE
TEST_REPORT_AFTER
TEST_PRINT_MEMORY_STATS
},

{
TEST_MESSAGE("Opetovne vlozeni elementu: 259")
TEST_OPERATION(set_insert)
TEST_INPUTS(259)
TEST_OUTPUT(0)
TEST_REPORT_AFTER
TEST_PRINT_MEMORY_STATS
},
